config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:edit, :update, :show, :destroy]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
    
  end

  def create
    #render plain: params[:article].inspect
    @article = Article.new(article_params)
    if @article.save
      # do something
      flash[:notice] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show
    
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = "Article was successfully deleted"
    redirect_to articles_path
  end


  private 
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2>The following errors have prevented the article from getting created:</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li> <%= msg %> </li>
    <% end %>
  </ul> 
<% end %>

<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %>
    </br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %>
    </br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "Back", articles_path %>

app/views/articles/edit.html.erb
<h1>Edit Selected Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<%= link_to "Create", new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>
  <% @articles.each do | article |%>
    <tr>
      <td><%= article.title %></td> 
      <td><%= article.description %></td>
      <td><%= link_to "Edit", edit_article_path(article) %></td>
      <td><%= link_to "Show", article_path(article) %></td>
      <td><%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure"} %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Showing selected article</h1>

<p>Title: <%= @article.title %> </p>
<p>Description: <%= @article.description %> </p>

<%= link_to "Edit", edit_article_path(@article) %> | 
<%= link_to "Back", articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <ul>
    <li><%= msg %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div style=''>
  <center>
  <h1>About Page</h1>
  <%= link_to 'Home', root_path %>
  <b><%= link_to 'About', about_path %></b>

  <br />

  <%= image_tag 'avatar.jpeg'%>
  </center>
</div>

app/views/pages/home.html.erb
<div style=''>
  <center>
  <h1>Welcome to Alpha Blog</h1>
  <b><%= link_to 'Home', root_path %></b> | 
  <%= link_to 'Blog', articles_path %> | 
  <%= link_to 'About', about_path %>
  <br />

  <%= image_tag 'avatar.jpeg'%>
  </center>
</div>